# Death Machine!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

--- 
baseurl: gh-pages
description: |
    Death Machine is an immersive First-Person Shooter game placed in a Sci-Fi World. 
    The player has the ability to wield a gun and traverse through a futuristic world where one is met by an Enemy, who is an agent with a gun.
    Enemy's are programmed to fire at the player until they have claimed vengence (health  for player is still being worked out). 
    The only way to escape their vengence is by shooting at them and reaching the final destination to win the game!
    The trick is that no indiciation of the Win Zone has been provided, so the player must explore the landscape to find the zone to win the game. 
    On entering the Win Zone, all Enemy's are auto-killed and you WIN THE GAME!
dimensions: 
  height: "8 metres"
  title: "Death Machine"
  width: "4 metres"
email: akhileshrao28@gmail.com
github_username: akhileshrao
html: "https://www.youtube.com/embed/VwyRyR_dhyE"
plugins: 
  - jekyll-feed
theme: minima
twitter_username: akhileshrao28
url: "https://akhileshrao.github.io"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
